version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
      - image: circleci/mongo
    steps:
      - checkout
      - run:
          name: Start app and test
          command: |
            yarn
            yarn run start & sleep 5
            curl http://localhost:3000/api/tags
            yarn run test
      - run:
          name: Trigger integration tests
          command: curl -X POST "https://circleci.com/api/v1.1/project/github/cooltushar/nodeapp?circle-token=efd766d2e56b51bd4f5e098d2c3dd2134ad1e529"